### ------------------------------------------------------------ NOTES

GET http://localhost:3001/api/v1/notes/

###

GET http://localhost:3001/api/v1/notes/1ddc9c43-105f-4955-b719-58db654e7f1a

### 

DELETE http://localhost:3001/api/v1/notes/5723bbe1-d8e7-448e-a8d5-fe6b9acd0f87

### 

DELETE http://localhost:3001/api/v1/notes/deleteAllNotes


### 

POST http://localhost:3001/api/v1/notes/ HTTP/1.1
content-type: application/json

{
    "body": "Fifth Note"
}

### 

PATCH http://localhost:3001/api/v1/notes/ HTTP/1.1
content-type: application/json

{
    "body": "Fifth Note EDITED!!"
}

### ------------------------------------------------------------ COMMENTS

GET http://localhost:3001/api/v1/comments/

###

GET http://localhost:3001/api/v1/comments/a8a12f20-b423-4ec4-9db7-c3b633d01e62

### 

DELETE http://localhost:3001/api/v1/comments/556e8368-b8a4-438f-8682-73e4253d8f8a

### 

DELETE http://localhost:3001/api/v1/comments/deleteAllComments


### 

POST http://localhost:3001/api/v1/comments/ HTTP/1.1
content-type: application/json

{
    "title": "UOOOOOOOO Comment",
    "description": "Testing out relations"
}

### 

PATCH http://localhost:3001/api/v1/comments/ HTTP/1.1
content-type: application/json

{   
    "id": "69d632f2-6c89-40eb-adf9-db39a2311383",
    "title": "Fourth Comment EDITTED!",
    "description": "This is the Fourth comment that's put into the DB"
}

###

GET http://localhost:3001/api/v1/comments/

### ------------------------------------------------------------ USERS

GET http://localhost:3001/api/v1/users/

###

GET http://localhost:3001/api/v1/users/getAllUsers/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4

###

GET http://localhost:3001/api/v1/users/getOneUser/c5d37029-18c8-47d5-a7e1-11b23d9c2116/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4

###

POST http://localhost:3001/api/v1/users/ HTTP/1.1
content-type: application/json

{
    "first_name": "Dagmawi",
    "last_name": "Babi",
    "email": "babii@gmail.com",
    "department": "SASS",
    "user_type": "employee"
}

###

POST http://localhost:3001/api/v1/users/createUser HTTP/1.1
content-type: application/json

{
    "first_name": "IE",
    "last_name": "EI",
    "email": "IE@gmail.com",
    "role": "software comp",
    "department": "SASS",
    "user_type": "employee",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4"
}


###

DELETE  http://localhost:3001/api/v1/users/deleteUser HTTP/1.1
content-type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "JohnDoe@gmail.com",
    "role": "software dev",
    "department": "SASS",
    "user_type": "employee",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4"
}

###

DELETE http://localhost:3001/api/v1/users/deleteAllUsers/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4


###

POST http://localhost:3001/api/v1/users/editUser HTTP/1.1
content-type: application/json

{
    "id": 6,
    "first_name": "John",
    "last_name": "Doe",
    "email": "JohnDoe@gmail.com",
    "role": "software dev",
    "department": "SASS",
    "user_type": "employee",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4"
}

###

POST http://localhost:3001/api/v1/users/loginUser HTTP/1.1
content-type: application/json

{   
    "first_name": "Dagmawi",
    "last_name": "Babi",
    "email": "dagmawi@gmail.com",
    "role": "software dev",
    "department": "SASS",
    "user_type": "employee"
}

###
    # "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRGFnbWF3aSIsImxhc3RfbmFtZSI6IkJhYmkiLCJlbWFpbCI6ImRhZ21hd2lAZ21haWwuY29tIiwicm9sZSI6InNvZnR3YXJlIGRldiIsImRlcGFydG1lbnQiOiJTQVNTIiwidXNlcl90eXBlIjoiZW1wbG95ZWUiLCJpYXQiOjE2ODk3NzA4MzIsImV4cCI6MTY5MDM3NTYzMn0.JtC09vGnkVfu9V7it0GqTnocMMtXMBzTrMjqpfyjkA4"

